# -- Display -------------------------------------------------------------------
set -g history-limit 25000
set -sg repeat-time 600       # increase repeat timeout
set -g focus-events on
setw -g automatic-rename on   # rename window to reflect current program
set -g set-titles on          # set terminal title
set -g display-panes-time 800 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time
set -g status-interval 1      # redraw status line every 1 seconds
set -g monitor-activity off
set -g visual-activity off

set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#000000,fg=#c1c1c1"
set -g status-left ""
set -g status-right " #S "
set -g status-right-style "bg=#000000,fg=#c1c1c1,bold"
set -g status-left-length 100
set -g status-right-length 100

set -g window-status-style "bg=#000000,fg=#c1c1c1"
set -g window-status-current-style "bg=#c1c1c1,fg=#000000,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

# -- Copy Mode ----------------------------------------------------------------
# Enter copy mode.
bind -n M-v copy-mode

# Vim-style selection in copy mode.
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi Escape send -X cancel

# -- Bind Keys ----------------------------------------------------------------
bind-key -r r source-file ~/.config/tmux/tmux.conf
bind-key d confirm-before -p "Kill tmux server? (y/n)" kill-server

bind-key -r g run-shell "tmux neww lazygit -p ."
bind-key -r h run-shell "tmux neww tmux-last-session-switcher.sh"
bind-key -r f run-shell "tmux neww tmux-sessionizer.sh"

bind-key -r 0 run-shell "tmux neww docker run -it --rm iypetrov/fireplace-test"
bind-key -r 1 run-shell "tmux neww ssh-sessionizer.sh"
bind-key -r 4 run-shell "tmux neww profilionizer.sh"
bind-key -r 9 run-shell 'tmux neww "k9s --kubeconfig=$(realpath "$(yq -r '\''.current as $c | .targets[] | select(.name == $c) | .kubeconfigPath'\'' ~/.config/knav/config.yaml | sed "s|^~|$HOME|")")"'
